### ISSUE TITLE
GSTerr10. For your information and agreement: The constitution of South Sudan as a new country triggers four changes at Level 4

### ISSUE THREAD

**Issue by lurdesrd** [tdwg/geoschemes#11]
1. New Level 4 Unit created for Sudan as a country  (SUD-SD) .
2. New Level 4 Unit created for South Sudan (SUD-SS).
3. Former Level 4 unid (SUD-OO) deprecated.
4. New limit between SUD-SD and SUD-SS

**Comment by rg02kg** [comment]
fully agree

**Comment by PacoPando** [comment]
Changes committed in working docs
