### ISSUE TITLE
GSTerr12. For your information and agreement: We keep level 4 TCS-NK ISO Code (AZ, Azerbaijan) despite being a territory in dispute

### ISSUE THREAD

**Issue by lurdesrd** [tdwg/geoschemes#13]
Nagorno-Karabakh, is a region disputed between Armenia and Azerbaijan for decades. The Republic of Artsakh controls the de facto self-governed Nagorno-Karabakh even though it is legally part of Azerbaijan.

Supplementary information:
https://en.wikipedia.org/wiki/Nagorno-Karabakh

**Comment by PacoPando** [comment]
As no comments have been received , we maintain our initial position and keep the WGSRPD 2 units s they appear there
