### ISSUE TITLE
GSTerr14. For your information and agreement: WIN-SV (St.Vincent) LEVEL 4 unit. Name changed to match the official denomination

### ISSUE THREAD

**Issue by lurdesrd** [tdwg/geoschemes#15]
Suggested change “St.Vincent” replace for “Saint Vincent and the Grenadines “ for level 4 unit  WIN-SV.
 
Supplementary information:
https://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines

**Comment by rg02kg** [comment]
Would there not need to be a space after the St. and officially it is "Saint Vincent"

**Comment by PacoPando** [comment]
Agreed. Changes committed in working documents

**Comment by PacoPando** [comment]
Name for unit "WIN-SV" Changed to "St. Vincent and the Grenadines" in the working documents. The use of "St." for "·Saint" is maintained flowing the rule stated on page 9 of the 2nd Ed. of the standard
