### ISSUE TITLE
GSTerr15. For your information and agreement: LSI-ET (East Timor) LEVEL 4 unit. ISOcode changed to TL.

### ISSUE THREAD

**Issue by lurdesrd** [tdwg/geoschemes#16]
The ISO standard changed this code in 2002 from TP to TL to reflect the official country denomination (Timor-Leste, in Portuguese).

**Comment by rg02kg** [comment]
Would we then not also need a West Timor (Indonesian province)

**Comment by PacoPando** [comment]
In the current standard (2.ed, 2000) West Timor is included in with the rest of the Lesser Sunda Islands (LSI-LS). That makes indeed an awkward division as there is no easy way to refer to Timor Is. as a whole. So, in line with the previous comment, we propose the following changes:

1. ISO Code for  LSI-ET changes to TL
2.  A new Level 4. unit is created for the rest of Timor (part of the Indonesian province of East Nusa Tenggara], with LSI-WT (as in West Timor)
3.  Limits of LSI-LS, changes to exclude the Indonesian part of Timor from this unit.
