### ISSUE TITLE
Add to India level 4 new provinces Jharkhand and Telangana

### ISSUE THREAD

**Issue by rg02kg** [tdwg/geoschemes#18]
Zaïre has now long changed to Democratic Republic of the Congo so we could use the long version or "DR Congo" (my preference) to distinguish it from "Congo" whose official name is Republic of the Congo.
Retain code ZAI as it is clearly distinct from CON.

**Comment by PacoPando** [comment]
The previous comment has been addressed under issue #17

**Comment by GMartSag** [comment]
Jharkhand is already in the WGSRPD (2 ed). The creation of the Telangana state triggers the following changes: 
1) a new level 4 unit for Telangana
2) a boundary change in IND-AP Andhra Pradesh
