### ISSUE TITLE
GSTerr1. New name for fomer Yugoslavia: Balkans or West Balkans?

### ISSUE THREAD

**Issue by PacoPando** [tdwg/geoschemes#2]
Yugoslavia no longer exists, a new name for level 3 unit  YUG is needed, and a new code too (BAK? WBK?)

Ref: Working table for level 3
https://docs.google.com/spreadsheets/d/1W1v_tAfMU1DsUcLJQVlO9cfBBZnvk6UNOdXMShVhJxA/edit#gid=2044344181

row 8

**Comment by rg02kg** [comment]
I would very much prefer Northwest Balkan or Northwest Balkan Peninsula and not change the code (we normally never do).
West Balkans would assume to include Albania.

**Comment by PacoPando** [comment]
Agreed, "Northwest Balkan" as name is more precise. However we believe that a change in level code 3 (Now NWB for YUG) is pertinent as Yugoslavia is no longer in existence and there are a few precedents in WGSRPR ed. 2 of level 3 coded changes
