### ISSUE TITLE
Türkiye for Turkey?

### ISSUE THREAD

**Issue by rg02kg** [tdwg/geoschemes#22]
Recently Turkey has requested its English name to be changed to Türkiye in the UN, should we change that or does it need more discussion?

**Comment by PacoPando** [comment]
I believe this needs more discussion and indeed a different approach, such as using a dual language system in referring to countries (English/Local language). I believe that going for local language for countries get us in  a slippery territory. For a start, the umlaut is not a diacritic in the English language, then if "Türkiye" why not "España", or "المغرب"?  I think a dual name system would be much more stable, usable and accepted.

**Comment by rg02kg** [comment]
https://www.aljazeera.com/news/2022/6/2/un-registers-turkiye-as-new-country-name-for-turkey

"Türkiye" is not a local name it is now the official English name used in the UN, which is normally the official name globally used

**Comment by PacoPando** [comment]
After some consultation we  agree with  rg02kg (whoever she or he is ;-)  proposal, and propose a name change for units TUE, TUR,  TUE-00 and TUR-00

**Comment by rg02kg** [comment]
rg02kg is Rafael Govaerts, dept.2, Kew Gardens

R.
