### ISSUE TITLE
Area name of AGE-SF and AGS-RN in Level4.xlsx

### ISSUE THREAD

**Issue by hkokubun2017** [tdwg/geoschemes#26]
I found that the area name of AGE-SF is Santa Fé, but the official name of the province is Santa Fe (without acute), and that of AGS-RN is Rio Negro instead of the official Río Negro (with acute). Getty Thesaurus of Geographic Names agrees on these, so the names need to be changed to the official spelling.
In the related topic, the column head of the name of Level4 area is currently "L4 country," and I think L4 area (as in Level3.xlsx) or L4 name would be more appropriate.

**Comment by GMartSag** [comment]
Agreed. Area names and column header modified.
