### ISSUE TITLE
GSTerr2. KRY as level 3 unit loses its ISO Code (Table 3 in WGSRPD 2) as now two countries dispute its territory or not?

### ISSUE THREAD

**Issue by lurdesrd** [tdwg/geoschemes#3]
Russia controls the de facto part of Crimea. Shall we follow the de jure or the de facto criterium?

**Comment by rg02kg** [comment]
Don't see any need to change KRY, like KRI it is part of another country but a very distinct photographic area.

**Comment by PacoPando** [comment]
We conclude that no changes are needed in this regard

**Comment by PacoPando** [comment]
We conclude that no changes are needed in this regard
