### ISSUE TITLE
GSTerr3. Shall we recognize South Ossetia as a new level 4 Unit? 

### ISSUE THREAD

**Issue by lurdesrd** [tdwg/geoschemes#4]
South Ossetia is considered Russian occupied territory by Georgia and as an independent country by a few countries.
See for instance https://en.wikipedia.org/wiki/South_Ossetia

**Comment by PacoPando** [comment]
This territory is not recognized by any significant number of countries and even less within the scope of the UN. Thus, we maintain the units in this region as they are in WGSRPD 2
