### ISSUE TITLE
GSTerr4. TCS LEVEL 3 Transcaucasus; TCS-AB (Abkhaziya) LEVEL 4

### ISSUE THREAD

**Issue by lurdesrd** [tdwg/geoschemes#5]
TCS LEVEL 3 Transcaucasus
TCS-AB (Abkhaziya) LEVEL 4
The cartographic limits of the Absajia region are discontinuous in google maps and the country to which it corresponds is not labeled. Does this region correspond to Georgia?

**Comment by PacoPando** [comment]
This territory is not recognized by any significant number of countries and even less within the scope of the UN. Thus, we maintain the units in this region as they are in WGSRPD 2
