### ISSUE TITLE
GSTerr5. For your information and agreement: Jilin Limits (China)

### ISSUE THREAD

**Issue by lurdesrd** [tdwg/geoschemes#6]
Limits represented in Map 7. China: _Levels 3 (named) and Level 4 (codes only)_. They do not correspond to the current state of these territories.

Supplementary information:
https://en.wikipedia.org/wiki/Jilin
https://en.wikipedia.org/wiki/Provinces_of_China.

**Comment by PacoPando** [comment]
Issue closed and re-opened as part of issue GSTerr17 #23
