### ISSUE TITLE
GSTerr8. For your information and agreement: L4 ISOcode  Navassa I. (Haiti)

### ISSUE THREAD

**Issue by lurdesrd** [tdwg/geoschemes#9]
Navassa I. as a level 4 unit changes its ISO Code (Table 4 in WGSRPD 2) since its territory belongs to the US.

Supplementary information:
https://en.wikipedia.org/wiki/Navassa_Island

**Comment by PacoPando** [comment]
Since no significative developments have occurred in this dispute  since the publication of the WGSRPD ed. 2, we opt for maintaining codes  and name as they were
